### ISSUE TITLE
Submission wizard - page 3

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-backend-gsa#26]
- Placeholder for fields should be there telling what valid inputs are (e.g. Uberon ID, DOID, NCBI    Taxon ID)
- For the species field how to ensure that a scientific name is used? Should we was of NVBI Taxon ID?
- We need to check if the provided field inputs are valid (e.g. Uberon ID, DOID etc)

**Comment by rykahsay** [comment]
@kmartinez834  can you provide example e.g. Uberon ID, DOID, NCBI Taxon ID

**Comment by rykahsay** [comment]
Let's leave disease and tissue information to be free text for now. For organism info, it requires tax_id now -- which gets validated.

**Comment by kmartinez834** [comment]
Spreadsheet with placeholder text: https://docs.google.com/spreadsheets/d/1A3IVeL3EMl6rGqANwxaXbsualz_b6piHIpY_6-dUKN8/edit?usp=sharing
