### ISSUE TITLE
Submission wizard - page 4

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-backend-gsa#27]
- Input fields should be validated -- PubMed ID, DOI, URL
- Keyword and experimental method should have a dropdown of existing terms and an other field (to     encourage reuse of existing terms over creating new once)

**Comment by ReneRanzinger** [comment]
- DOI validation is not working. (e.g. DOI for GlyGen paper 10.1093/glycob/cwz080 )
- I can add a paper with just type PubMed but no ID (same for DOI)
- Keyword and experimental method should have a dropdown of existing terms and an other field (to encourage reuse of existing terms over creating new once)

**Comment by rykahsay** [comment]
>>I can add a paper with just type PubMed but no ID (same for DOI)
  
 I don't know when you tested it but this was fixed last time I pushed.


>>Keyword and experimental method should have a dropdown of existing terms and an other field (to encourage reuse of existing terms over creating new once)

I am making a new ticket for this and that will be done in the next version
