### ISSUE TITLE
Page 4: Required fields and delete action

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-backend-gsa#31]
* All fields on page 4 (publication, experimental data, experimental method, keywords) are marked as required. But at least experimental data and database reference should not
* Delete icons for experimental method and keywords are not working
* When entering the page the publication type is set to PubMed (OK). When adding a paper the fields gets emptied out. Why not keep PubMed as default?

**Comment by rykahsay** [comment]
Was not able to reproduce this part:
>> Delete icons for experimental method and keywords are not working

**Comment by ReneRanzinger** [comment]
This part is working now. Maybe not all code was deployed 9 days ago.
