### ISSUE TITLE
Unknown position for peptide and proteins

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-backend-gsa#32]
Currently we enforce a position for protein and peptide. But as we know its possible to just not know the position. How can the user enter this? Suggestion: Tickbox "Position unknown" which disables start and end position and overwrites their validation.

**Comment by rykahsay** [comment]
I have made start_pos and end_pos not required

**Comment by ReneRanzinger** [comment]
That is a solution. But please make sure that either none or both are provided. Just one of them is not valid OR we define just one as start=end.
