### ISSUE TITLE
GlycoTree validation not working

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-backend-gsa#34]
Using GlyTouCan ID G32082KI

Step 3 says:

```
Errors

    No errors found.

Rule Violations

    No rule violations found.
```

However the sandbox has caveats:

https://glygen.ccrc.uga.edu/sandbox/explore.html?G32082KI

**Comment by kmartinez834** [comment]
Special character (beta) in rule violation is not appearing correctly:
- residue N301 (&beta;-D-GlcpNAc) has an abiotic glycosyl linkage

Should look like SandBox:
![image](https://user-images.githubusercontent.com/90285371/187971745-a66e7450-972c-4263-a10f-4c5ddcd5fb19.png)

**Comment by rykahsay** [comment]
Looks like it that's what I get from the validation API

**Comment by ReneRanzinger** [comment]
The &beta; is the html encoding for this special character. It probably gets encoding somewhere along the web service call. The same is probably happen with alpha as well.
