### ISSUE TITLE
Validate GlycoCT/WURCS with GlyTouCan ID

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-backend-gsa#39]
If user provides GlyTouCan ID we need to check if GlycoCT/WURCS is the corresponding sequence.

**Comment by kmartinez834** [comment]
Incorrect sequence gives the following error message:
Alert!
Invalid glycan sequence

Change to:
Alert!
Incorrect glycan sequence for GlyTouCan accession
