### ISSUE TITLE
Update user profile

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-backend-gsa#6]
Currently its not possible to update the user profile. After login there should be an entry point for this either in the menu or the dashboard (see #4).

We should also ask for additional information:
* Institute or organization
* Department
* URL (LinkedIn or homepage)

**Comment by ReneRanzinger** [comment]
Currently if I am clicking submit nothing (seem to) happens. It should show an feedback along the line of "Your account information has been updated"

**Comment by rykahsay** [comment]
Was not able to reproduce this issue -- it works fine for me

<img width="520" alt="image" src="https://user-images.githubusercontent.com/20584876/179220330-40ea0cbd-b077-4af7-8654-6562a88b4f71.png">
