### ISSUE TITLE
Details View

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-backend-gsa#60]
Make it obvious that GSA contains records and not unique molecules. Make the following changes to details view and submission wizard (Step 1):
- Change "Submission Type" to "Record Type"
- Change "GlycoProtein" to "Protein Glycosylation Site" 
- Change "GlycoPeptide" to "Peptide Glycosylation Site"?

**Comment by kmartinez834** [comment]
@ReneRanzinger  We discussed changing "GlycoProtein" to "Glycosylation Site" in the last meeting. Do we need to make changes to "GlycoPeptide" and "Glycolipid" as well?

**Comment by ReneRanzinger** [comment]
@kmartinez834 Not for lipid. We store the entire glycolipid (usually just one  glycan/site). How about "Protein glycosylation site" and "Peptide glycosylation site"?

**Comment by kmartinez834** [comment]
@ReneRanzinger Ok, making updates to the original issue text
