### ISSUE TITLE
Production site - new submission issues

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-backend-gsa#70]
Test submission: GSA076505

1. I used GlyTouCan **G17689DH** for this example.  There is no GlyTouCan accession listed on the My Submissions page:
![image](https://user-images.githubusercontent.com/90285371/192852620-91327ad1-5ca3-4119-a5f8-79ec12d8112b.png)

2. The API says the GlyTouCan accession is **G96921ZU**
![image](https://user-images.githubusercontent.com/90285371/192853229-16e17f75-ced9-40c0-bf83-e9496793a974.png)

3. When I searched for GSA076505 on the home page, I get two different results for the same GSA ID (with different GlyTouCan accessions).  However, both link to https://gsa.glygen.org/detail/GSA076505, which lists GlyTouCan ac  **G96921ZU**
![image](https://user-images.githubusercontent.com/90285371/192853564-097c6bf8-e566-4ba5-b763-d48aa86a94ee.png)

4. Information on details page does not match what I submitted.  My submission details were overridden.
5. I made a second submission, GSA076506, using GlyTouCan G49108TO.  The resulting details page was overridden with a completely different structure.
![image](https://user-images.githubusercontent.com/90285371/192855236-eb3dbcc7-e93b-452f-91de-be9268703619.png)

6. "Created on" time is not correct, should be 13:41:07 and 13:54:17
![image](https://user-images.githubusercontent.com/90285371/192857269-3bb3e2ec-7529-4c64-aaad-f56e3dd41b3b.png)

**Comment by rykahsay** [comment]
I have created a new release (1.2) and the GSA record IDs have changed (but the selected records that should be on the top are still on the top). If you want to map GSA IDs between 1.1 and 1.2, look at these files and use the first column as an anchor).


/data/shared/gsa/releases/data/v-1.1/sort_score.txt
/data/shared/gsa/releases/data/v-1.2/sort_score.txt
